version: '3.8'

services:
  web:
    build:
      context: src/main
      dockerfile: Dockerfile
    image: shreedharkc/shreedhar-experiment-websocket-app:latest
    ports:
      - "5000:5000"
    env_file:
      - src/main/.env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
    command: gunicorn --worker-class=eventlet -w 1 --bind=0.0.0.0:5000 app:app